Todo

* Big Features
  --

* Code
  - [ ] Have a config file load static assets so you don't have to list all of them in the main html file.
** Templating
   - [ ] Have a way of being able to call a template from within a template.
   - [ ] Extend handlebars to allow looping through models without having to call toJSON on each model.
   - [ ] Compile templates server-side.


* Misc
  - The user should be able to quickly navigate various entries or
    browse through them all one-by-one without much delay. The use of
    modals doesn't allow this due to the time it takes for it to pop
    up.

* Guidelines
  --

* NEW
  Don't use a Calendar model. The main Collection model (for holding
  Day objects) should not separate based on any block length (e.g.,
  week, month, year). It should contain an arbitrary number of days
  (adjustable).

* NOW
  - Work on the Calendar Model. It should contain the Days collection.
  - [tp.html, views.js] Work on getting the Journal view to render.
  - Render empty day blocks. How do we render empty day blocks? How do
    we know if a block is empty? Should we instantiate "empty"
    objects? This seems unhygenic (generating models we may or may not
    save to the server). Think about this.
